CREATE DATABASE HOME_AI_DB;

CREATE SCHEMA HOME_AI_SCHEMA;

create or replace TABLE ROOMS_LISTINGS (
	LISTING_URL VARCHAR(16777216),
	LOCATION VARCHAR(16777216),
	PRICE NUMBER(38,0),
	LISTING_DATE DATE,
	ROOM_COUNT NUMBER(2,0),
	BATH_COUNT NUMBER(2,0),
	PEOPLE_COUNT NUMBER(2,0),
	DESCRIPTION_SUMMARY VARCHAR(16777216),
	SOURCE VARCHAR(16777216),
	CONTACT VARCHAR(16777216),
	LAUNDRY_AVAILABLE VARCHAR(16777216),
	REPORT_COUNT NUMBER(1,0),
	IMAGE_URL VARCHAR(16777216),
	ROOM_TYPE VARCHAR(16777216),
	OTHER_DETAILS VARCHAR(16777216),
	LISTING_VEC VECTOR(FLOAT, 1024),
	ROOM_ID NUMBER(38,0)
);

CREATE OR REPLACE TABLE home_ai_db.home_ai_schema.user_profile(
    user_email VARCHAR,
    user_password VARCHAR,
    first_name VARCHAR,
    last_name VARCHAR
);

CREATE OR REPLACE TABLE home_ai_db.home_ai_schema.user_feedback(
    user_email VARCHAR,
    listing_url VARCHAR,
    comments VARCHAR
);

CREATE OR REPLACE TABLE home_ai_db.home_ai_schema.user_preference(
    user_email VARCHAR,
    budget NUMBER(5,1),
    room_type VARCHAR(15),
    region VARCHAR(100),
    people_count NUMBER(2)
);

CREATE OR REPLACE TABLE HOME_AI_DB.HOME_AI_SCHEMA.EMBEDDING_TASK_LOG (
    LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    TYPE STRING,
    STATUS_MESSAGE STRING
);

CREATE OR REPLACE SEQUENCE rooms_listings_seq;