-- Task to run the embedding generation procedure for listings
CREATE OR REPLACE TASK HOME_AI_DB.HOME_AI_SCHEMA.RUN_EMBEDDINGS_TASK
  WAREHOUSE = 'MY_WAREHOUSE'
  SCHEDULE = 'USING CRON 35 17 * * * America/New_York'
AS
  CALL HOME_AI_DB.HOME_AI_SCHEMA.CREATE_LISTING_EMBEDDINGS();

-- Resume the task
ALTER TASK HOME_AI_DB.HOME_AI_SCHEMA.RUN_EMBEDDINGS_TASK RESUME;