const STATE_CITY_MAP = {
    MA: [
      "Boston",
      "Roxbury Crossing",
      "Brighton",
      "Mission Hill",
      "Watertown",
      "Wellesley Hills",
      "Roxbury",
      "Melrose",
      "Newtonville",
      "Newton",
      "East Arlington",
      "Spencer",
      "Leominster",
      "North Billerica",
      "Jamaica Plain",
      "Salem"
    ],
    NY: [
      "Brooklyn",
      "Queens",
      "Deer Park",
      "Sunnyside",
      "Ridgewood",
      "Bronx",
      "Whitestone",
      "East Harlem",
      "Byron",
      "Utica",
      "Sunset Park",
      "Olean",
      "Orchard Park",
      "Brentwood",
      "Jamestown",
      "Canandaigua"
    ],
    WA: [
      "Seattle",
      "Millcreek",
      "Poulsbo",
      "Victory Heights",
      "Lake Forest Park",
      "Olympia",
      "Lakewood",
      "Greenwood",
      "Camano Island",
      "Burien",
      "White Center",
      "Sunnyside",
      "Ballard",
      "North Delridge",
      "Issaquah"
    ],
    FL: [
      "Tampa",
      "Miami",
      "Davie",
      "Port Richey",
      "St. Petersburg",
      "Temple Terrace",
      "Westchester",
      "Kendall",
      "Port Charlotte",
      "Seffner",
      "Dunedin",
      "Lake Worth",
      "Cutler Bay",
      "North Port",
      "Ellenton"
    ],
    CA: [
      "San Francisco",
      "Coronado",
      "Fremont",
      "Mountain View",
      "Pasadena",
      "San Jose",
      "West Los Angeles",
      "Santa Cruz",
      "Westwood",
      "Gaslamp",
      "Pacific Beach",
      "Imperial Beach",
      "El Segundo",
      "Carpinteria",
      "Upland"
    ]
  };
  export default STATE_CITY_MAP;